### ISSUE TITLE
does not work with Rails 2.3.11 undefined method `custom_amazon_ses_mailer=' for ActionMailer::Base:Class (NoMethodError) 

### ISSUE THREAD

**Issue by innovia** [drewblas/aws-ses#39]
i get undefined method `custom_amazon_ses_mailer=' for ActionMailer::Base:Class (NoMethodError)

i've set up my config/environments/production.rb

config.after_initialize do
  ActionMailer::Base.delivery_method = :amazon_ses
  ActionMailer::Base.custom_amazon_ses_mailer = AWS::SES::Base.new(
        :access_key_id     => 'my aws key',
        :secret_access_key => 'my aws secret'
)
end

I tested on irb and its working fine
